Add rule for React Hooks
palantir/tslint-react pull request #204
Opened 2019-02-13 07:26 UTC by Gelio

I created [a rule for detecting improper uses of React Hooks](https://github.com/Gelio/tslint-react-hooks). For more information about the rule take a look at the [tslint-react-hooks](https://github.com/Gelio/tslint-react-hooks) repository.

This PR integrates the `react-hooks-nesting` into this repository.

I built `tslint-react` with the newly added rule and it works correctly with both `react-hooks-nesting` and built in this repository (example that reports both `react-hooks-nesting` for using a hook inside `if` and `jsx-wrap-multiline`):

![image](https://user-images.githubusercontent.com/889383/52694029-bc135a80-2f68-11e9-9110-396a9c893904.png)

`tslint.json` contained only the following:

```json
{
  "extends": "tslint-react"
}
```

This PR is related to #186.

2019-02-13 07:26 UTC, palantirtech commented
Thanks for your interest in [palantir/tslint-react](https://github.com/palantir/tslint-react), @Gelio! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2019-02-13 11:30 UTC, gibbok approved these changes
LGTM 👍

2019-02-27 14:09 UTC, gibbok commented
Would be fantastic to include your PR in `tslint-react`. Any update on this? Thanks for your great work!

2019-02-27 14:46 UTC, Gelio commented
@gibbok Thanks you 🙂 I see many people giving a thumbs-up on this PR, but a maintainer needs to review it. Considering the fact [that Palantir is moving development resources from TSLint to ESLint](https://medium.com/palantir/tslint-in-2019-1a144c2317a9), it may take a while 😟

2019-03-12 23:24 UTC, adidahiya requested changes
We're not going to add a new dependency to this package like this. If you want, you can port your rule implementation to this repo.

2019-03-13 14:29 UTC, Gelio commented
That's a pity. I would rather keep the hooks rule in my repo to be able to develop it freely. I will close this PR

2019-03-13 14:29 UTC, closed without merging

2019-03-13 15:35 UTC, adidahiya commented
Sure, you're free to do that, and users can install your package and use `extends: "tslint-react-hooks"`... that's exactly what that feature was designed for.

2019-06-24 01:40 UTC, sonhanguyen commented
@Gelio do you mind me doing this copy paste job?

2019-06-24 08:55 UTC, Gelio commented
@sonhanguyen Hey :wave: Yes, I do mind. I would rather not copy paste the rule's code over to this project as it would lead to duplication. Updates would have to be applied twice. Thus, I would rather keep the hooks rule in the [tslint-react-hooks](https://github.com/Gelio/tslint-react-hooks) repository

Thanks for reaching out and suggesting :slightly_smiling_face: